### ISSUE TITLE
fix appveyor test for sasmodels win 64 python 3 (Trac #1050)

### ISSUE THREAD

**Issue by pkienzle** [SasView/sasmodels#165]
The broken test is a blocker for release even though we are not using python 3.6 since it can hide breakage we care about in python 2.7.

Either remove the breaking test from appveyor, and make this ticket a sasview 5.0 blocker, or better yet, fix the code (if the code is the problem) or the test (if it is an appveyor configuration problem).

https://ci.appveyor.com/project/ajj/sasmodels

Looks like a 32 vs 64 bit linkage problem:

```text
core_shell_parallelepiped, Kernel: dll
======================================================================
ERROR [0.047s]: test_cylinder_dll (__main__._hide_model_case_from_nose.<locals>.ModelTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\projects\sasmodels\sasmodels\model_test.py", line 212, in run_all
    results = [self.run_one(model, test) for test in tests]
  File "C:\projects\sasmodels\sasmodels\model_test.py", line 212, in <listcomp>
    results = [self.run_one(model, test) for test in tests]
  File "C:\projects\sasmodels\sasmodels\model_test.py", line 296, in run_one
    actual = call_kernel(kernel, pars)
  File "C:\projects\sasmodels\sasmodels\direct_model.py", line 63, in call_kernel
    return calculator(call_details, values, cutoff, is_magnetic)
  File "C:\projects\sasmodels\sasmodels\kerneldll.py", line 404, in __call__
    kernel(*args) # type: ignore
OSError: exception: access violation reading 0x00000000A6CBC748
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "C:\projects\sasmodels\sasmodels\model_test.py", line 232, in run_all
    annotate_exception(self.test_name)
  File "C:\projects\sasmodels\sasmodels\exception.py", line 41, in annotate_exception
    raise OSError(str(exc) + " " + msg)
OSError: exception: access violation reading 0x00000000A6CBC748 Model: cylinder, Kernel: dll
```

Migrated from http://trac.sasview.org/ticket/1050
```json
{
    "status": "closed",
    "changetime": "2018-01-19T18:35:36",
    "_ts": "2018-01-19 18:35:36.344686+00:00",
    "description": "The broken test is a blocker for release even though we are not using python 3.6 since it can hide breakage we care about in python 2.7.\n\nEither remove the breaking test from appveyor, and make this ticket a sasview 5.0 blocker, or better yet, fix the code (if the code is the problem) or the test (if it is an appveyor configuration problem).\n\nhttps://ci.appveyor.com/project/ajj/sasmodels\n\nLooks like a 32 vs 64 bit linkage problem:\n{{{\ncore_shell_parallelepiped, Kernel: dll\n======================================================================\nERROR [0.047s]: test_cylinder_dll (__main__._hide_model_case_from_nose.<locals>.ModelTestCase)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File \"C:\\projects\\sasmodels\\sasmodels\\model_test.py\", line 212, in run_all\n    results = [self.run_one(model, test) for test in tests]\n  File \"C:\\projects\\sasmodels\\sasmodels\\model_test.py\", line 212, in <listcomp>\n    results = [self.run_one(model, test) for test in tests]\n  File \"C:\\projects\\sasmodels\\sasmodels\\model_test.py\", line 296, in run_one\n    actual = call_kernel(kernel, pars)\n  File \"C:\\projects\\sasmodels\\sasmodels\\direct_model.py\", line 63, in call_kernel\n    return calculator(call_details, values, cutoff, is_magnetic)\n  File \"C:\\projects\\sasmodels\\sasmodels\\kerneldll.py\", line 404, in __call__\n    kernel(*args) # type: ignore\nOSError: exception: access violation reading 0x00000000A6CBC748\nDuring handling of the above exception, another exception occurred:\nTraceback (most recent call last):\n  File \"C:\\projects\\sasmodels\\sasmodels\\model_test.py\", line 232, in run_all\n    annotate_exception(self.test_name)\n  File \"C:\\projects\\sasmodels\\sasmodels\\exception.py\", line 41, in annotate_exception\n    raise OSError(str(exc) + \" \" + msg)\nOSError: exception: access violation reading 0x00000000A6CBC748 Model: cylinder, Kernel: dll\n}}}",
    "reporter": "pkienzle",
    "cc": "",
    "resolution": "fixed",
    "workpackage": "SasView Bug Fixing",
    "time": "2017-12-15T16:50:51",
    "component": "sasmodels",
    "summary": "fix appveyor test for sasmodels win 64 python 3",
    "priority": "blocker",
    "keywords": "",
    "milestone": "SasView 4.2.0",
    "owner": "",
    "type": "defect"
}
```

**Comment by pkienzle** [comment]
Trac update at `2018/01/19 18:35:36`: 
* **pkienzle** changed resolution from "" to "fixed"
* **pkienzle** changed status from "new" to "closed"
