### ISSUE TITLE
improve support for tgamma and other missing function (Trac #564)

### ISSUE THREAD

**Issue by smk78** [SasView/sasmodels#275]
Executing make clean html from Windows CMD or Git Bash shell:

python genmodel.py ../sasmodels/models/fractal.py model/fractal.rst
Traceback (most recent call last):
  File "genmodel.py", line 103, in <module>
    plot_1d(model, opts, ax1d)
  File "genmodel.py", line 47, in plot_1d
    Iq1D = calculator()
  File "e:\sasviewdevelopment\sasmodels\sasmodels\direct_model.py", line 214, in __call__
    return self._calc_theory(pars, cutoff=self.cutoff)
  File "e:\sasviewdevelopment\sasmodels\sasmodels\direct_model.py", line 174, in _calc_theory
    self._kernel = self._model.make_kernel(self._kernel_inputs)  # pylint: disable=attribute-dedata_type
  File "e:\sasviewdevelopment\sasmodels\sasmodels\kernelcl.py", line 320, in make_kernel
    self.fast)
  File "e:\sasviewdevelopment\sasmodels\sasmodels\kernelcl.py", line 224, in compile_program
    program = compile_model(self.get_context(dtype), source, dtype, fast)
  File "e:\sasviewdevelopment\sasmodels\sasmodels\kernelcl.py", line 150, in compile_model
    program = cl.Program(context, source).build(options=options)
  File "c:\Anaconda\lib\site-packages\pyopencl\__init__.py", line 213, in build
    options=options, source=self._source)
  File "c:\Anaconda\lib\site-packages\pyopencl\__init__.py", line 253, in _build_and_catch_errors
    raise err
pyopencl.RuntimeError: clBuildProgram failed: build program failure -

Build on <pyopencl.Device 'Oland                                                          ' on 'AMD Accelerated Parallel Processing' at 0xa9f5210>:

"C:/Users/smk78/AppData/Local/Temp\OCL7C94.tmp.cl", line 210: error:
          storage-class specifiers extern/static/register not allowed for
          variables
        static float SQTPI = 2.50662827463100050242E0f;
        ^

"C:/Users/smk78/AppData/Local/Temp\OCL7C94.tmp.cl", line 232: error:
          identifier "SQTPI" is undefined
        y = SQTPI * y * w;
            ^

"C:/Users/smk78/AppData/Local/Temp\OCL7C94.tmp.cl", line 238: error:
          storage-class specifiers extern/static/register not allowed for
          variables
        static float LOGPI = 1.14472988584940017414f;
        ^

"C:/Users/smk78/AppData/Local/Temp\OCL7C94.tmp.cl", line 291: warning: goto
          statement may cause irreducible control flow
                        goto small;
                        ^

"C:/Users/smk78/AppData/Local/Temp\OCL7C94.tmp.cl", line 299: warning: goto
          statement may cause irreducible control flow
                        goto small;
                        ^

3 errors detected in the compilation of "C:/Users/smk78/AppData/Local/Temp\OCL7C94.tmp.cl".

Frontend phase failed compilation.

(options: -I c:\anaconda\lib\site-packages\pyopencl\cl)
(source saved as c:\users\smk78\appdata\local\temp\tmpbnhiza.cl)
make: *** [model/fractal.rst] Error 1

smk78@NDW1000 /e/sasviewdevelopment/sasmodels/doc (master)
$

Migrated from http://trac.sasview.org/ticket/564
```json
{
    "status": "reopened",
    "changetime": "2019-03-02T00:37:03",
    "_ts": "2019-03-02 00:37:03.557746+00:00",
    "description": "Executing make clean html from Windows CMD or Git Bash shell:\n\npython genmodel.py ../sasmodels/models/fractal.py model/fractal.rst\nTraceback (most recent call last):\n  File \"genmodel.py\", line 103, in <module>\n    plot_1d(model, opts, ax1d)\n  File \"genmodel.py\", line 47, in plot_1d\n    Iq1D = calculator()\n  File \"e:\\sasviewdevelopment\\sasmodels\\sasmodels\\direct_model.py\", line 214, in __call__\n    return self._calc_theory(pars, cutoff=self.cutoff)\n  File \"e:\\sasviewdevelopment\\sasmodels\\sasmodels\\direct_model.py\", line 174, in _calc_theory\n    self._kernel = self._model.make_kernel(self._kernel_inputs)  # pylint: disable=attribute-dedata_type\n  File \"e:\\sasviewdevelopment\\sasmodels\\sasmodels\\kernelcl.py\", line 320, in make_kernel\n    self.fast)\n  File \"e:\\sasviewdevelopment\\sasmodels\\sasmodels\\kernelcl.py\", line 224, in compile_program\n    program = compile_model(self.get_context(dtype), source, dtype, fast)\n  File \"e:\\sasviewdevelopment\\sasmodels\\sasmodels\\kernelcl.py\", line 150, in compile_model\n    program = cl.Program(context, source).build(options=options)\n  File \"c:\\Anaconda\\lib\\site-packages\\pyopencl\\__init__.py\", line 213, in build\n    options=options, source=self._source)\n  File \"c:\\Anaconda\\lib\\site-packages\\pyopencl\\__init__.py\", line 253, in _build_and_catch_errors\n    raise err\npyopencl.RuntimeError: clBuildProgram failed: build program failure -\n\nBuild on <pyopencl.Device 'Oland                                                          ' on 'AMD Accelerated Parallel Processing' at 0xa9f5210>:\n\n\"C:/Users/smk78/AppData/Local/Temp\\OCL7C94.tmp.cl\", line 210: error:\n          storage-class specifiers extern/static/register not allowed for\n          variables\n        static float SQTPI = 2.50662827463100050242E0f;\n        ^\n\n\"C:/Users/smk78/AppData/Local/Temp\\OCL7C94.tmp.cl\", line 232: error:\n          identifier \"SQTPI\" is undefined\n        y = SQTPI * y * w;\n            ^\n\n\"C:/Users/smk78/AppData/Local/Temp\\OCL7C94.tmp.cl\", line 238: error:\n          storage-class specifiers extern/static/register not allowed for\n          variables\n        static float LOGPI = 1.14472988584940017414f;\n        ^\n\n\"C:/Users/smk78/AppData/Local/Temp\\OCL7C94.tmp.cl\", line 291: warning: goto\n          statement may cause irreducible control flow\n                        goto small;\n                        ^\n\n\"C:/Users/smk78/AppData/Local/Temp\\OCL7C94.tmp.cl\", line 299: warning: goto\n          statement may cause irreducible control flow\n                        goto small;\n                        ^\n\n3 errors detected in the compilation of \"C:/Users/smk78/AppData/Local/Temp\\OCL7C94.tmp.cl\".\n\nFrontend phase failed compilation.\n\n(options: -I c:\\anaconda\\lib\\site-packages\\pyopencl\\cl)\n(source saved as c:\\users\\smk78\\appdata\\local\\temp\\tmpbnhiza.cl)\nmake: *** [model/fractal.rst] Error 1\n\nsmk78@NDW1000 /e/sasviewdevelopment/sasmodels/doc (master)\n$\n",
    "reporter": "smk78",
    "cc": "",
    "resolution": "",
    "workpackage": "SasModels Infrastructure",
    "time": "2016-04-26T15:20:26",
    "component": "SasView",
    "summary": "improve support for tgamma and other missing function",
    "priority": "minor",
    "keywords": "",
    "milestone": "SasView Next Release +1",
    "owner": "",
    "type": "defect"
}
```

**Comment by pkienzle** [comment]
Another alternative: scan the c code and warn if there is anything that looks like a function we have defined in our special functions library.
